apiVersion: v1
kind: Service
metadata:
  name: nats-exporter
  namespace: monitoring
  labels:
    app: nats-exporter
spec:
  selector:
    app: nats-exporter
  ports:
    - name: metrics
      port: 7777
      targetPort: metrics
