apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana/app.yaml
  - longhorn/app.yaml
  - pinger/app.yaml
  - cloudflared/app.yaml
  - prometheus/app.yaml
  - test-app/app.yaml
