apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - appproject-infra.yaml
    - app.yaml              # l’Application d’ArgoCD (grafana)
    - dashboard-pinger.yaml # el ConfigMap amb el dashboard embebit
